version: '3.9'
services:
  wordpress:
    build: .
    container_name: wp-php
    depends_on: [db]
    volumes: [./wordpress:/var/www/html]
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wpdb
  nginx:
    image: nginx:latest
    container_name: wp-nginx
    ports: ["8080:80"]
    volumes:
      - ./wordpress:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on: [wordpress]
  db:
    image: mariadb:10.6
    container_name: wp-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wpdb
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
    volumes: [db_data:/var/lib/mysql]
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wp-pma
    restart: always
    ports: ["8081:80"]
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpass
    depends_on: [db]
volumes:
  db_data:
